/** Auto-generated by scripts/download-nav-assets.mjs — do not edit manually */
export const navIconAssets: Record<string, string | string[]> = {
  "aboutUs": "/images/wow/nav/icons/aboutUs.png",
  "strategyCentre": "/images/wow/nav/icons/strategyCentre.png",
  "teamExperts": "/images/wow/nav/icons/teamExperts.png",
  "whySmbs": "/images/wow/nav/icons/whySmbs.png",
  "partners": "/images/wow/nav/icons/partners.png",
  "whyUs": "/images/wow/nav/icons/whyUs.png",
  "buildLaunch": "/images/wow/nav/icons/buildLaunch.png",
  "softwareTechnology": "/images/wow/nav/icons/softwareTechnology.png",
  "marketingGrowth": "/images/wow/nav/icons/marketingGrowth.png",
  "socialCommunity": [
    "/images/wow/nav/icons/socialCommunity-0.png",
    "/images/wow/nav/icons/socialCommunity-1.png",
    "/images/wow/nav/icons/socialCommunity-2.png",
    "/images/wow/nav/icons/socialCommunity-3.png"
  ],
  "salesRevenue": "/images/wow/nav/icons/salesRevenue.png",
  "aiAutomation": "/images/wow/nav/icons/aiAutomation.png",
  "brandingCreative": "/images/wow/nav/icons/brandingCreative.png",
  "hostingInfrastructure": "/images/wow/nav/icons/hostingInfrastructure.png",
  "learningEvents": "/images/wow/nav/icons/learningEvents.png",
  "startupLaunchPackage": "/images/wow/nav/icons/startupLaunchPackage.png",
  "businessGrowthPackage": "/images/wow/nav/icons/businessGrowthPackage.png",
  "digitalTransformationPackage": "/images/wow/nav/icons/digitalTransformationPackage.png",
  "aiAutomationPackage": "/images/wow/nav/icons/aiAutomationPackage.png",
  "saasProductDevelopmentPackage": "/images/wow/nav/icons/saasProductDevelopmentPackage.png",
  "brandAuthorityPackage": "/images/wow/nav/icons/brandAuthorityPackage.png",
  "salesAccelerationPackage": "/images/wow/nav/icons/salesAccelerationPackage.png",
  "enterpriseInfrastructurePackage": "/images/wow/nav/icons/enterpriseInfrastructurePackage.png",
  "portfolio": "/images/wow/nav/icons/portfolio.png",
  "recentWorks": "/images/wow/nav/icons/recentWorks.png",
  "clients": [
    "/images/wow/nav/icons/clients-0.png",
    "/images/wow/nav/icons/clients-1.png"
  ],
  "partnerNetwork": "/images/wow/nav/icons/partnerNetwork.png",
  "locations": "/images/wow/nav/icons/locations.png",
  "startupsEntrepreneurs": "/images/wow/nav/icons/startupsEntrepreneurs.png",
  "professionalServices": "/images/wow/nav/icons/professionalServices.png",
  "retailEcommerce": [
    "/images/wow/nav/icons/retailEcommerce-0.png",
    "/images/wow/nav/icons/retailEcommerce-1.png",
    "/images/wow/nav/icons/retailEcommerce-2.png"
  ],
  "healthcareWellness": "/images/wow/nav/icons/healthcareWellness.png",
  "hospitalityTourism": "/images/wow/nav/icons/hospitalityTourism.png",
  "financeRealEstate": "/images/wow/nav/icons/financeRealEstate.png",
  "organizationsNonprofits": "/images/wow/nav/icons/organizationsNonprofits.png",
  "educationTraining": "/images/wow/nav/icons/educationTraining.png",
  "technologySaas": "/images/wow/nav/icons/technologySaas.png",
  "meet": "/images/wow/nav/icons/meet.png",
  "thinkTank": "/images/wow/nav/icons/thinkTank.png",
  "quotation": "/images/wow/nav/icons/quotation.png",
  "clientPortal": "/images/wow/nav/icons/clientPortal.png",
  "whiteLabel": "/images/wow/nav/icons/whiteLabel.png",
  "affiliate": "/images/wow/nav/icons/affiliate.png",
  "insights": "/images/wow/nav/icons/insights.png",
  "careers": "/images/wow/nav/icons/careers.png",
  "helpSupport": "/images/wow/nav/icons/helpSupport.png",
  "brandKit": "/images/wow/nav/icons/brandKit.png",
  "websiteGrowthEnginePackage": "/images/wow/nav/icons/websiteGrowthEnginePackage.png"
}

export const navDivisionAssets: Record<string, string[]> = {
  "softwareWow": [
    "/images/wow/nav/divisions/softwareWow-0.png",
    "/images/wow/nav/divisions/softwareWow-1.png",
    "/images/wow/nav/divisions/softwareWow-2.png"
  ],
  "wowMarketing": [
    "/images/wow/nav/divisions/wowMarketing-0.png",
    "/images/wow/nav/divisions/wowMarketing-1.png",
    "/images/wow/nav/divisions/wowMarketing-2.png"
  ],
  "wowDesign": [
    "/images/wow/nav/divisions/wowDesign-0.png",
    "/images/wow/nav/divisions/wowDesign-1.png",
    "/images/wow/nav/divisions/wowDesign-2.png"
  ],
  "wowIntelligence": [
    "/images/wow/nav/divisions/wowIntelligence-0.png",
    "/images/wow/nav/divisions/wowIntelligence-1.png",
    "/images/wow/nav/divisions/wowIntelligence-2.png"
  ],
  "wowSocial": [
    "/images/wow/nav/divisions/wowSocial-0.png",
    "/images/wow/nav/divisions/wowSocial-1.png",
    "/images/wow/nav/divisions/wowSocial-2.png"
  ],
  "wowAccelerate": [
    "/images/wow/nav/divisions/wowAccelerate-0.png",
    "/images/wow/nav/divisions/wowAccelerate-1.png",
    "/images/wow/nav/divisions/wowAccelerate-2.png"
  ],
  "wowWebsites": [
    "/images/wow/nav/divisions/wowWebsites-0.png",
    "/images/wow/nav/divisions/wowWebsites-1.png",
    "/images/wow/nav/divisions/wowWebsites-2.png"
  ],
  "wowImpact": [
    "/images/wow/nav/divisions/wowImpact-0.png",
    "/images/wow/nav/divisions/wowImpact-1.png",
    "/images/wow/nav/divisions/wowImpact-2.png"
  ],
  "wowHost": [
    "/images/wow/nav/divisions/wowHost-0.png",
    "/images/wow/nav/divisions/wowHost-1.png",
    "/images/wow/nav/divisions/wowHost-2.png",
    "/images/wow/nav/divisions/wowHost-3.png"
  ]
}

export const navCardImages = {
  default: '/images/wow/nav/cards/default.jpg',
  exploreDefault: '/images/wow/nav/cards/explore-default.jpg',
} as const
