/** Strapi auto-generated UID placeholder when no custom slug is set. */
export const STRAPI_AUTO_PROJECT_SLUG = 'wowsuperagencyproject';

export function slugifyTitle(title: string): string {
  return title
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

export function isAutoGeneratedProjectSlug(slug?: string | null): boolean {
  return !slug?.trim() || slug.trim() === STRAPI_AUTO_PROJECT_SLUG;
}

/** Public URL slug for any case study project from CMS. */
export function resolveCaseStudySlug(project: {
  slug?: string | null;
  title: string;
}): string {
  const cmsSlug = project.slug?.trim();
  if (cmsSlug && !isAutoGeneratedProjectSlug(cmsSlug)) {
    return cmsSlug;
  }

  return slugifyTitle(project.title);
}

export function matchesCaseStudySlug(
  project: { slug?: string | null; title: string },
  requestedSlug: string,
): boolean {
  const normalized = requestedSlug.trim().toLowerCase();
  if (!normalized) return false;

  const cmsSlug = project.slug?.trim().toLowerCase();
  if (cmsSlug && cmsSlug === normalized) return true;

  return slugifyTitle(project.title) === normalized;
}
