/**
 * AUTO-GENERATED by scripts/audit-frontend-hero-images.ts — do not edit manually.
 * Re-run: npm run audit:hero-images
 */

export type HeroImageEntry = { path: string; alt: string };
export type HeroLayout = 'none' | 'single' | 'dual' | 'multi' | 'slider' | 'hover';

export type HeroImageManifestEntry = {
  layout: HeroLayout;
  images: HeroImageEntry[];
  note?: string;
};

const img = (path: string, alt: string): HeroImageEntry => ({ path, alt });

export const HERO_IMAGE_MANIFEST: Record<string, HeroImageManifestEntry> = {
  'about': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'about-strategy-centre': {
    layout: 'single',
    images: [
      img("/images/wow/hero-banner.jpg", "WOW Strategy Centre"),
    ],
  },
  'about-why-smbs': {
    layout: 'single',
    images: [
      img("/images/home-5/hero-img.png", "Growing SMB teams working with WOW"),
    ],
  },
  'about-partners': {
    layout: 'slider',
    images: [
      img("/images/wow/Hero/client/Avatar.png", "Avatar"),
      img("/images/wow/Hero/client/Avatar (1).png", "Avatar (1)"),
      img("/images/wow/Hero/client/Avatar (2).png", "Avatar (2)"),
    ],
  },
  'about-why-us': {
    layout: 'dual',
    images: [
      img("/images/hero-img/startup-hero-1.jpg", "startup hero 1"),
      img("/images/hero-img/startup-hero-2.jpg", "startup hero 2"),
    ],
  },
  'team': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'portfolio': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'portfolio-recent': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'clients': {
    layout: 'multi',
    images: [
      img("/images/wow/Hero/project/case-study/ccg.png", "ccg"),
      img("/images/wow/Hero/project/case-study/davinci.png", "davinci"),
      img("/images/wow/Hero/project/case-study/InityInc.png", "InityInc"),
      img("/images/wow/Hero/project/case-study/yodoner.png", "yodoner"),
      img("/images/wow/Hero/project/case-study/smartek.png", "smartek"),
      img("/images/wow/Hero/project/case-study/creshendo.png", "creshendo"),
    ],
  },
  'partners': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/software&technology.png", "software&technology"),
      img("/images/wow/nav/cards/Accelerate.png", "Growth and partnership collaboration"),
    ],
  },
  'locations': {
    layout: 'multi',
    images: [
      img("/images/wow/locations/landmarks/NYC.png", "NYC"),
      img("/images/wow/locations/landmarks/Paros.png", "Paros"),
      img("/images/wow/locations/landmarks/Rio.png", "Rio"),
      img("/images/wow/locations/landmarks/Rome.png", "Rome"),
      img("/images/wow/locations/landmarks/Sydney.png", "Sydney"),
      img("/images/wow/locations/landmarks/UK.png", "UK"),
    ],
  },
  'industries': {
    layout: 'single',
    images: [
      img("/images/home-5/hero-img.png", "Industries hero"),
    ],
  },
  'professional-services': {
    layout: 'hover',
    images: [
      img("/images/wow/nav/cards/pexels-fauxels-3183132 1.png", "Professional services team collaboration"),
      img("/images/wow/nav/cards/Business growth 1.png", "Professional services team collaboration"),
      img("/images/wow/nav/cards/Hub.png", "Business growth for professional firms"),
    ],
  },
  'startups-and-entrepreneurs': {
    layout: 'single',
    images: [
      img("/images/wow/nav/cards/Startup laiunch 1.png", "Startup laiunch 1"),
    ],
  },
  'retail-and-ecommerce': {
    layout: 'none',
    images: [],
    note: "Text-only hero in the hero block — marquee images use the **gallery** section, not hero → images.",
  },
  'healthcare-and-wellness': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/pexels-fauxels-3183132 1.png", "pexels fauxels 3183132 1"),
      img("/images/wow/nav/cards/pexels-cottonbro-4069290 1.png", "pexels cottonbro 4069290 1"),
    ],
  },
  'hospitality-and-tourism': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'finance-and-real-estate': {
    layout: 'single',
    images: [
      img("/images/wow/nav/cards/sales-profit-numbers-changing-on-monitor-after-glo-2026-01-08-02-14-54-utc 1.png", "sales profit numbers changing on monitor after glo 2026 01 08 02 14 54 utc 1"),
    ],
  },
  'organizations-and-nonprofits': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'education-and-training': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'technology-and-saas': {
    layout: 'multi',
    images: [
      img("/images/wow/nav/cards/digital transofrmation 1.png", "digital transofrmation 1"),
      img("/images/wow/nav/cards/Intelligent.png", "Intelligent"),
      img("/images/wow/nav/cards/Accelerate.png", "Accelerate"),
      img("/images/wow/nav/cards/software&technology.png", "software&technology"),
      img("/images/wow/nav/cards/AI Automation 1.png", "AI Automation 1"),
      img("/images/wow/nav/cards/Website.png", "Website"),
    ],
  },
  'build-and-launch': {
    layout: 'dual',
    images: [
      img("/images/hero-img/startup-hero-1.jpg", "startup hero 1"),
      img("/images/hero-img/startup-hero-2.jpg", "startup hero 2"),
    ],
  },
  'marketing-and-growth': {
    layout: 'single',
    images: [
      img("/images/hero-img/video-img.png", "Marketing and growth overview"),
    ],
  },
  'software-and-technology': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'social-and-community': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/Social.png", "Social content and community engagement"),
      img("/images/wow/nav/cards/social media start 1.png", "social media start 1"),
    ],
  },
  'ai-and-automation': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'sales-and-revenue': {
    layout: 'single',
    images: [
      img("/images/wow/nav/cards/Sales Acceleration 1.png", "Sales Acceleration 1"),
    ],
  },
  'branding-and-creative': {
    layout: 'multi',
    images: [
      img("/images/wow/nav/cards/Branding & Creative 1.png", "Branding & Creative 1"),
      img("/images/wow/nav/cards/Design.png", "Design"),
      img("/images/wow/nav/cards/Marketing.png", "Marketing"),
      img("/images/wow/nav/cards/Website.png", "Website"),
      img("/images/wow/nav/cards/Social.png", "Social"),
      img("/images/wow/nav/cards/Impact.png", "Impact"),
    ],
  },
  'hosting-and-infrastructure': {
    layout: 'dual',
    images: [
      img("/images/hero-img/startup-hero-1.jpg", "startup hero 1"),
      img("/images/hero-img/startup-hero-2.jpg", "startup hero 2"),
    ],
  },
  'learning-and-events': {
    layout: 'single',
    images: [
      img("/images/wow/Hero/devision/Education.jpg", "Education"),
    ],
  },
  'startup-launch': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/Startup laiunch 1.png", "Startup laiunch 1"),
      img("/images/wow/nav/cards/build&lanch.png", "build&lanch"),
    ],
  },
  'business-growth': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/Business growth 1.png", "Business growth 1"),
      img("/images/wow/nav/cards/Accelerate.png", "Accelerate"),
    ],
  },
  'digital-transformation': {
    layout: 'multi',
    images: [
      img("/images/wow/nav/cards/digital transofrmation 1.png", "digital transofrmation 1"),
      img("/images/wow/nav/cards/Intelligent.png", "Intelligent"),
      img("/images/wow/nav/cards/Accelerate.png", "Accelerate"),
      img("/images/wow/nav/cards/software&technology.png", "software&technology"),
      img("/images/wow/nav/cards/AI Automation 1.png", "AI Automation 1"),
      img("/images/wow/nav/cards/Website.png", "Website"),
    ],
  },
  'ai-automation': {
    layout: 'single',
    images: [
      img("/images/wow/foryou/branimage.png", "branimage"),
    ],
  },
  'brand-authority': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/social media start 1.png", "social media start 1"),
      img("/images/wow/nav/cards/Branding & Creative 1.png", "Branding & Creative 1"),
    ],
  },
  'saas-product-development': {
    layout: 'dual',
    images: [
      img("/images/wow/nav/cards/SaaS Dev 1.png", "SaaS Dev 1"),
      img("/images/wow/nav/cards/Softwaerwow.png", "Softwaerwow"),
    ],
  },
  'website-growth-engine': {
    layout: 'multi',
    images: [
      img("/images/wow/nav/cards/Website.png", "Website"),
      img("/images/wow/nav/cards/Websit groeh 1.png", "Websit groeh 1"),
      img("/images/wow/nav/cards/Host.png", "Host"),
      img("/images/wow/nav/cards/Design.png", "Design"),
      img("/images/wow/nav/cards/Accelerate.png", "Accelerate"),
      img("/images/wow/nav/cards/Intelligent.png", "Intelligent"),
    ],
  },
  'sales-acceleration': {
    layout: 'single',
    images: [
      img("/images/wow/nav/cards/Sales Acceleration 1.png", "Sales Acceleration 1"),
    ],
  },
  'enterprise-infrastructure': {
    layout: 'hover',
    images: [
      img("/images/wow/nav/cards/Host.png", "WOW Host infrastructure and hosting"),
      img("/images/wow/nav/cards/software&technology.png", "WOW Host infrastructure and hosting"),
      img("/images/wow/nav/cards/Intelligent.png", "Software and technology systems"),
    ],
  },
  'meet': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'thinktank': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'quotation': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'whitelabel': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'affiliate': {
    layout: 'dual',
    images: [
      img("/images/wow/Hero/career/career (2).png", "career (2)"),
      img("/images/wow/Hero/career/career (1).png", "Professional working at a desk"),
    ],
  },
  'helpsupport': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'brandkit': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'blog': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'career': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
  'clientportal': {
    layout: 'none',
    images: [],
    note: "Text-only hero — leave **hero → images** empty.",
  },
};

const NONE: HeroImageManifestEntry = { layout: 'none', images: [], note: 'Text-only hero — leave **hero → images** empty.' };

export function getHeroImagesForPage(slug: string): HeroImageManifestEntry {
  return HERO_IMAGE_MANIFEST[slug] ?? NONE;
}
